version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: ''

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

build: off

test_script:
  - node --version && npm --version
  - npm test

cache:
  - node_modules            # local npm modules

matrix:
  fast_finish: true
